; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = build

[env]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
extra_scripts = 
	pre:../../pio-tools/buildscript_versioning.py
	merge_firmware.py

lib_extra_dirs =
	../../lib

board_build.filesystem = spiffs
board_build.partitions = partitions.csv

[env:busware-tul-c3-thelsing-coupler]
board = seeed_xiao_esp32c3
; board = esp32-c3-devkitm-1
; board = esp32-c3-devkitc-02
monitor_speed = 115200
# slow upload speed but most compatible
upload_speed = 115200
upload_flags =
  write_flash
  0x0
  ../../firmware/busware-tul-c3-thelsing-coupler.factory.bin
lib_deps =
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
  https://github.com/tostmann/knx.git
  # Improv Wi‑Fi serial configuration helper library (provides ImprovWiFiLibrary.h)
  https://github.com/jnthas/Improv-WiFi-Library.git

build_flags = 
  -DMASK_VERSION=0x091A
  -Wno-unknown-pragmas
  -DKNX_TUNNELING=10
  -DKNX_LED=4
  -DKNX_SERIAL=Serial0
  -DKNX_BAUDRATE=38400
  -DDEBUG_TP_FRAMES -DKNX_LOG_TUNNELING
  -DNCN5120
  -DMY_FRIENDLY_NAME='"busware - TUL"'
